# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_room_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[((b'Customer',), b'Customer'), ((b'Frontdesk',), b'Frontdesk'), ((b'Concierge',), b'Concierge'), ((b'Activitiesdesk',), b'Activitiesdesk'), ((b'Operator',), b'Operator')], default=(b'Customer',), max_length=20),
        ),
    ]
