# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20180903_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Room'),
        ),
    ]
