# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Theme')),
            ],
        ),
    ]
